#!/bin/bash
set -e

echo "[router] Starting routing configuration for {{hostname}}"

# -------------------------------------------------------
# 1. Enable IPv4 forwarding
#    (also set via sysctl in docker-compose, but belt-and-suspenders)
# -------------------------------------------------------
echo 1 > /proc/sys/net/ipv4/ip_forward
sysctl -w net.ipv4.ip_forward=1 2>/dev/null || true

echo "[router] IP forwarding enabled"

# -------------------------------------------------------
# 2. Wait briefly for all interfaces to be ready
# -------------------------------------------------------
sleep 1

# -------------------------------------------------------
# 3. Configure each interface with its IP + bring it up
#    Then add the connected subnet route.
#
#    Generated by generator.py from config.interfaces:
#    One line per interface → eth0, eth1, eth2, ...
# -------------------------------------------------------
{{interfaces}}

echo "[router] Interface configuration applied"

# -------------------------------------------------------
# 4. Set up NAT/masquerading so hosts on internal networks
#    can reach external networks through this router.
#    Uses iptables MASQUERADE on all forwarded traffic.
# -------------------------------------------------------
{{#enable_nat}}
iptables -t nat -A POSTROUTING -j MASQUERADE 2>/dev/null || true
iptables -A FORWARD -j ACCEPT 2>/dev/null || true
echo "[router] NAT/masquerade enabled"
{{/enable_nat}}

# -------------------------------------------------------
# 5. Log final routing table for debugging
# -------------------------------------------------------
echo "[router] Routing table:"
ip route show

echo "[router] Interface addresses:"
ip addr show

echo "[router] Configuration complete for {{hostname}}"

# Keep the container running
exec tail -f /dev/null