worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream backend {
{{upstream_algorithm}}
{{upstream_servers}}
    }

    server {
        listen {{listen_port}};
        server_name {{domain}};

        location / {
            proxy_pass http://backend;
        }
    }
}